# Generated by Django 5.1.2 on 2024-11-04 12:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Retirado', 'Retirado'), ('Manutenção', 'Manutenção')], default='Disponível', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_login', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Retirada', 'Retirada'), ('Devolução', 'Devolução')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.equipamento')),
            ],
        ),
    ]
