# Generated by Django 5.1.2 on 2024-11-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_usuario', models.CharField(max_length=15, unique=True)),
                ('nome_usuario', models.CharField(max_length=50)),
                ('turno_usuario', models.CharField(choices=[('T1', 'Manhã'), ('T2', 'Tarde'), ('T3', 'Noite')], max_length=2)),
                ('coordenador', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
