# Generated by Django 5.1.2 on 2024-11-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_usuariosistema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosistema',
            name='cargo',
        ),
        migrations.AddField(
            model_name='usuariosistema',
            name='turno_usuario',
            field=models.CharField(choices=[('T1', 'Manhã'), ('T2', 'Tarde'), ('T3', 'Noite')], default='T1', max_length=2),
            preserve_default=False,
        ),
    ]
