# Generated by Django 5.1.2 on 2024-11-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_remove_usuariosistema_cargo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioSistema',
        ),
    ]
