# Generated by Django 5.1.2 on 2025-01-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_delete_usuariosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotransacao',
            name='login_registrado',
            field=models.CharField(default='desconhecido', max_length=100),
        ),
    ]
